// Navbar with Mega Menu Vue3/Navbar.vue
<script setup>
import {
    ref,
    onMounted
} from 'vue';
import Preline from "preline";


const isOpen = ref(false);

const toggleMenu = () => {
    isOpen.value = !isOpen.value;
};

const closeMobileMenu = () => {
    isOpen.value = false;
};

onMounted(() => {
    initFlowbite();
});
</script>

<template>
    <nav class="bg-beige-300 py-4 sticky w-full top-0 z-10">
        <div class="container flex items-center justify-between">
            <div class="flex-shrink-0 flex gap-6 xl:gap-14 items-center">
                <img data-v-cb8ae5f9="" loading="lazy" alt="GelLogo" class="w-[180px]" src="https://i.imghippo.com/files/LzYzY1720858499.png">
                <div class="hs-dropdown [--strategy:static] sm:[--strategy:absolute] [--adaptive:none] sm:[--trigger:hover] hidden lg:block">
                    <button class="text-black-900 text-base font-bold flex items-center gap-1 py-4">Mega Menu
                        <img loading="lazy" :src="$page.props.assetURL ? $page.props.assetURL + '/web-assets/WebRevamp/arrowdown.svg' : '../../web-assets/WebRevamp/arrowdown.svg'" alt="arrowdown" class="">
                    </button>
                    <div class="hs-dropdown-menu transition-[opacity,margin] sm:border duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 hidden z-10 sm:mt-3 bg-white sm:shadow-md rounded-lg py-2 sm:px-2 dark:bg-neutral-800 sm:dark:border dark:border-neutral-700 dark:divide-neutral-700 sm:absolute sm:left-1/2 sm:transform sm:-translate-x-1/2 w-full container">
                        <div class="container mx-auto">
                            <div class="sm:grid sm:grid-cols-3">
                                <div class="flex flex-col">
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        About
                                    </a>
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Services
                                    </a>
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Customer Story
                                    </a>
                                </div>
    
                                <div class="flex flex-col">
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Careers
                                    </a>
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Careers: Overview
                                    </a>
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Careers: Apply
                                    </a>
                                </div>
    
                                <div class="flex flex-col">
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Log In
                                    </a>
                                    <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300" href="#">
                                        Sign Up
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="hidden lg:flex gap-1 xl:gap-6">
                <div class="flex">
                    <ul class="flex space-x-4 items-center">
                        <li>
                            <router-link to="#Corporate" class="text-black-900 text-base font-bold">Sample Link</router-link>
                        </li>
                        <li>
                            <router-link to="#Instructor" class="text-black-900 text-base font-bold">Sample Link 2</router-link>
                        </li>
                    </ul>
                </div>
                <div class="hidden lg:block">
                    <div class="flex items-center space-x-4">
                        <router-link to="#Login" class="rounded-lg text-black-900 text-base font-semibold py-2.5 px-6 hover:text-black-500 flex gap-2 items-center border border-transparent hover:border-black-900 cursor-pointer transition-all duration-300 ease-in-out">
                            Login
                            <img loading="lazy" :src="$page.props.assetURL ? $page.props.assetURL + '/web-assets/Arrow-Up.svg' : '../../web-assets/Arrow-Up.svg'" alt="Arrow-Up svg" class="">
                        </router-link>
                    </div>
                </div>
                <div class="hidden lg:block">
                    <div class="flex items-center space-x-4">
                        <router-link to="#Register" class="rounded-lg border border-black-800 text-black-900 text-base font-semibold py-2.5 px-6 hover:text-black-500 cursor-pointer">Register</router-link>
                    </div>
                </div>
            </div>
            <div class="lg:hidden">
                <button @click="toggleMenu" class="block text-black-500 focus:outline-none">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path v-if="isOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                        <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                </button>
            </div>
        </div>
        <!-- mobile menu -->
        <transition enter-active-class="transition-all ease-out duration-700" enter-from-class="opacity-0 max-h-0" enter-to-class="opacity-100 max-h-[400px]" leave-active-class="transition-all ease-in duration-700" leave-from-class="opacity-100 max-h-[400px]" leave-to-class="opacity-0 max-h-0">
            <div v-show="isOpen" class="absolute right-0 w-full bg-beige-300 rounded-b-lg shadow-lg z-50 lg:hidden mt-4 overflow-hidden">
                <ul class="container flex flex-col space-y-2 items-center px-5 py-3">
                    <li class="py-3 w-full">
                        <router-link to="#Corporate" @click="closeMobileMenu" class="text-black-900 text-base font-medium block">
                            Sample Link
                        </router-link>
                    </li>
                    <li class="py-3 w-full">
                        <router-link to="#Instructor" @click="closeMobileMenu" class="text-black-900 text-base font-medium block">
                            Sample Link
                        </router-link>
                    </li>
                    <li class="py-3 w-full">
                        <router-link to="#Login" @click="closeMobileMenu" class="text-black-900 text-base font-medium block">
                            Login
                        </router-link>
                    </li>
                    <li class="py-3 w-full">
                        <router-link to="#Register" @click="closeMobileMenu" class="text-black-900 text-base font-medium block">
                            Register
                        </router-link>
                    </li>
                </ul>
            </div>
        </transition>
    </nav>
</template>

<style scoped>
.transition-all {
    transition-property: all;
}

.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.3s;
}

.fade-enter,
.fade-leave-to {
    opacity: 0;
}
</style>

// Navbar Responsive React Next/navbar.jsx
"use client";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import logo from "../public/Images/ImperialHQLogo.png"

const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    const [isServicesOpen, setIsServicesOpen] = useState(false);
    const [open, setOpen] = useState(false);
    const dropdownRef = useRef(null);

    const toggleMenu = () => {
        setIsOpen(!isOpen);
    };

    const toggleServices = () => {
        setIsServicesOpen(!isServicesOpen);
    };

    useEffect(() => {
        const handleClickOutside = (event) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
                setIsServicesOpen(false);
            }
        };

        document.addEventListener("mousedown", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    const serviceItems = [
        { name: "LMS Solutions", href: "#solutions" },
        { name: "Custom e-Learning", href: "#e-Learning" },
        { name: "Certification Programmes ", href: "#Certification" },
    ];
    const closeMobileMenu = () => {
        setIsOpen(false);
        // You can also close other mobile-specific menus here if needed
    };
    return (
        <>
            <nav className="bg-Blue-100 py-4 sticky w-full top-0 z-10">
                <div className="container flex items-center justify-between">
                    <div className="flex-shrink-0">
                        <Link href="/">
                            <img className="w-[200px] h-[50px]" src={logo.src} alt="logo" />
                        </Link>
                    </div>
                    <div className="hidden xl:block">
                        <ul className="flex space-x-4 items-center">
                            <li>
                                <Link href="#chooseus" className="text-black-900 text-base font-medium mx-4">Why choose us</Link>
                            </li>
                            <li>
                                <Link href="#services" className="text-black-900 text-base font-medium mx-4">Essential Offerings</Link>
                            </li>
                            <li className="py-4 relative flex items-center" onMouseEnter={() => setOpen(true)}
                                onMouseLeave={() => setOpen(false)}
                            >
                                <a className="text-black-900 text-base font-medium" href="#0" aria-expanded={open}>
                                    Services
                                </a>
                                <button className="shrink-0 p-1" aria-expanded={open} onClick={(e) => {
                                    e.preventDefault();
                                    setOpen(!open);
                                }}
                                >
                                    <span className="sr-only">Show submenu for "Flyout Menu"</span>
                                    <svg className={`fill-current h-4 w-4 transition-transform duration-300 ${open ? 'rotate-180' : ''}`} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                                    </svg>
                                </button>
                                {/* 2nd level menu */}
                                <div className="relative">
                                    <ul className={`absolute top-[30px] left-[-50px] left-1/2 transform -translate-x-1/2 min-w-[300px] bg-white border border-slate-200 p-2 rounded-lg shadow-xl ${open ? 'block' : 'hidden'}`}>
                                        <div className="grid p-2 gap-x-4">
                                            {serviceItems.map((item, index) => (
                                                <li key={item.name}>
                                                    <Link href={item.href} className={`bg-white hover:bg-beige-100 py-3 px-4 block whitespace-no-wrap rounded-xl ${index === 0 ? '' : index === serviceItems.length - 1 ? '' : ''}`}>
                                                        {item.name}
                                                    </Link>
                                                </li>
                                            ))}
                                        </div>
                                    </ul>
                                </div>
                            </li>

                            <li>
                                <Link href="#reviews" className="text-black-900 text-base font-medium mx-4">Testimonials</Link>
                            </li>
                            <li>
                                <Link href="#faqs" className="text-black-900 text-base font-medium mx-4">FAQ's</Link>
                            </li>
                        </ul>
                    </div>
                    <div className="hidden xl:block">
                        <div className="flex items-center space-x-4">
                            <Link href="#contact" className="rounded-lg border border-black-800 text-black-900 text-base font-semibold py-2.5 px-6 hover:text-black-500">Contact</Link>
                        </div>
                    </div>
                    <div className="xl:hidden">
                        <button onClick={toggleMenu} className="block text-black-500 focus:outline-none">
                            <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                {isOpen ? (
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                ) : (
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                                )}
                            </svg>
                        </button>
                    </div>
                </div>
                {/* mobile menu */}
                <div className={`${isOpen ? "absolute right-0 mt-2 w-full bg-white rounded-xl shadow-lg z-50 px-3 py-3" : "hidden"} xl:hidden mt-4`}>
                    <ul className="flex flex-col space-y-2 items-center">
                        <li className="py-3 w-full">
                            <Link href="#chooseus" onClick={closeMobileMenu} className=" text-black-900 text-base font-medium block">
                                Why choose us
                            </Link>
                        </li>
                        <li className="py-3 w-full">
                            <Link href="#services" onClick={closeMobileMenu} className=" text-black-900 text-base font-medium block">
                                Essential Offerings
                            </Link>
                        </li>
                        <li className="py-3 w-full">
                            <button onClick={toggleServices} className=" text-black-900 text-base font-medium w-full text-left flex justify-between items-center">
                                Services
                                <svg className={`w-4 h-4 transition-transform ${isServicesOpen ? "transform rotate-180" : ""}`} fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
                                </svg>
                            </button>
                            {isServicesOpen && (
                                <ul className="mt-2 ml-4">
                                    {serviceItems.map((item) => (
                                        <li key={item.name} className="py-2">
                                            <Link href={item.href} onClick={closeMobileMenu} className="text-black-900 text-sm font-medium block">
                                                {item.name}
                                            </Link>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </li>
                        <li className="py-3 w-full">
                            <Link href="#reviews" onClick={closeMobileMenu} className=" text-black-900 text-base font-medium block">
                                Testimonials
                            </Link>
                        </li>
                        <li className="py-3 w-full">
                            <Link href="#faqs" onClick={closeMobileMenu} className=" text-black-900 text-base font-medium block">
                                FAQ's
                            </Link>
                        </li>
                        <li className="py-3 w-full">
                            <Link href="#contact" onClick={closeMobileMenu} className=" text-black-900 text-base font-medium block">
                                Contact
                            </Link>
                        </li>
                    </ul>
                </div>
            </nav>
        </>
    );
};

export default Navbar;
